version: '3.9'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - kong-network

networks:
  kong-network:
    driver: bridge
