version: '3.9'

services:
  # Spring Boot Application
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - kong-network

  # Kong Database (Postgres)
  kong-database:
    image: postgres:15
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5433:5432"
    networks:
      - kong-network

  # Kong Gateway
  kong:
    image: kong/kong-gateway:3.8.0.0
    volumes:
      - ./kong/kong.yaml:/etc/kong/kong.yml
    depends_on:
      - kong-database
    networks:
      - kong-network

networks:
  kong-network:
    driver: bridge
