version: "3.8"

services:
  kong-db:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  kong-migrations:
    image: kong:latest
    depends_on:
      - kong-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
    command: ["kong", "migrations", "bootstrap"]

  kong:
    image: kong:latest
    depends_on:
      - kong-migrations
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8002:8002"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8002"
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443"
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml
    command: >
      sh -c "
      kong config db_import /etc/kong/kong.yml &&
      kong reload"
