version: '3.8'

services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: kong
    ports:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql

  kong-migrations:
    image: kong:latest
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: root_password
      KONG_PG_USER: root
      KONG_PG_DATABASE: kong
    entrypoint: ["kong", "migrations", "bootstrap"]

  kong:
    image: kong:latest
    depends_on:
      - db
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: root_password
      KONG_PG_USER: root
      KONG_PG_DATABASE: kong
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./kong/kong.yaml:/usr/local/kong/declarative/kong.yaml

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8080"

volumes:
  mysql_data:
